version: '2'

services:
  cgi:
    container_name: php7.2
    image: reader1/php_ext_redis_swoole:7.2
    restart: always 
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ../myspace:/www/workspace/
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
  nginx:
    container_name: nginx_v1
    image: reader1/openresty:1
    restart: always
    volumes: 
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ../myspace:/www/workspace/:ro
    ports: 
      - 80:80
      - 443:443
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.6
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./runtime/var_lib_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zydc
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./runtime/var_lib_redis:/data
    command: redis-server --appendonly yes
